url = input()
from pytube import YouTube
yt = YouTube(url)
if yt.description.endswith('Auto-generated by YouTube.'):
    title, artist = yt.description.split('\n')[2].split(' · ')
    print(title)
    print(artist)
else:
    raise ValueError